/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ProveedoresC;
import controlador.bancosC;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Mauro
 */
public class ModificarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProveedor
     */
    public ModificarProveedor() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rutLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        telefonoTF = new javax.swing.JTextField();
        correoTF = new javax.swing.JTextField();
        direccionTF = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        estadoCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(rutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 11, 156, 19));
        getContentPane().add(nombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 36, 114, -1));
        getContentPane().add(telefonoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 62, 114, -1));
        getContentPane().add(correoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 88, 114, -1));
        getContentPane().add(direccionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 114, 114, -1));

        saveButton.setText("Guardar");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 200, -1, -1));

        closeButton.setText("Cerrar");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 200, -1, -1));
        getContentPane().add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, 221, 22));

        estadoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        getContentPane().add(estadoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 140, 114, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/256x287.jpg"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        setVisible(false);
        ProveedoresC.buscar();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        var response = ProveedoresC.modificarProveedor(this.rutLabel.getText(), this.nombreTF.getText(), this.telefonoTF.getText(), this.correoTF.getText(), this.direccionTF.getText(), this.estadoCB.getSelectedIndex() );
         if(response)
            this.resultLabel.setText("Proveedor modificado exitosamente");
        else
            this.resultLabel.setText("No fue posible modificar el proveedor");
    }//GEN-LAST:event_saveButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProveedor().setVisible(true);
            }
        });
    }

    public JTextField getCorreoTF() {
        return correoTF;
    }

    public void setCorreoTF(JTextField correoTF) {
        this.correoTF = correoTF;
    }

    public JTextField getDireccionTF() {
        return direccionTF;
    }

    public void setDireccionTF(JTextField direccionTF) {
        this.direccionTF = direccionTF;
    }

    public JTextField getNombreTF() {
        return nombreTF;
    }

    public void setNombreTF(JTextField nombreTF) {
        this.nombreTF = nombreTF;
    }

    public JLabel getResultLabel() {
        return resultLabel;
    }

    public void setResultLabel(JLabel resultLabel) {
        this.resultLabel = resultLabel;
    }

    public JLabel getRutLabel() {
        return rutLabel;
    }

    public void setRutLabel(JLabel rutLabel) {
        this.rutLabel = rutLabel;
    }

    public JTextField getTelefonoTF() {
        return telefonoTF;
    }

    public void setTelefonoTF(JTextField telefonoTF) {
        this.telefonoTF = telefonoTF;
    }

    public JComboBox<String> getEstadoCB() {
        return estadoCB;
    }

    public void setEstadoCB(JComboBox<String> estadoCB) {
        this.estadoCB = estadoCB;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton closeButton;
    public javax.swing.JTextField correoTF;
    public javax.swing.JTextField direccionTF;
    public javax.swing.JComboBox<String> estadoCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField nombreTF;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel rutLabel;
    public javax.swing.JButton saveButton;
    public javax.swing.JTextField telefonoTF;
    // End of variables declaration//GEN-END:variables
}
