/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author marce
 */
public class modificarUser extends javax.swing.JFrame {

    /**
     * Creates new form modificarUser
     */
    public modificarUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mUsuario = new javax.swing.JTextField();
        mContraseña = new javax.swing.JTextField();
        labelUs = new javax.swing.JLabel();
        labelCo = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(mUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));
        getContentPane().add(mContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 100, -1));

        labelUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelUs.setForeground(new java.awt.Color(255, 255, 255));
        labelUs.setText("Usuario");
        getContentPane().add(labelUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, -1));

        labelCo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCo.setForeground(new java.awt.Color(255, 255, 255));
        labelCo.setText("Contraseña");
        getContentPane().add(labelCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(estadoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/spiral380.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCo;
    private javax.swing.JLabel labelUs;
    private javax.swing.JTextField mContraseña;
    private javax.swing.JTextField mUsuario;
    // End of variables declaration//GEN-END:variables
}
