/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author usuario
 */
public class SuperAdm extends javax.swing.JFrame {

    /**
     * Creates new form MenuPpal
     */
    public SuperAdm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        superAdmPestañas = new javax.swing.JTabbedPane();
        superAdmIngresoVenta = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dreamgiftTelefono = new java.awt.TextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dreamgiftTotal = new java.awt.TextField();
        dreamgiftNumeroPedido = new java.awt.TextField();
        dreamgiftBusquedaRut = new java.awt.TextField();
        dreamgiftRut = new java.awt.TextField();
        dreamgiftDireccion = new java.awt.TextField();
        dreamgiftMail = new java.awt.TextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dreamgiftventasPend = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        dreamgiftNombre = new java.awt.TextField();
        dreamgiftRrss = new java.awt.TextField();
        dreamgiftFechaNac = new java.awt.TextField();
        dreamgiftDestinat = new java.awt.TextField();
        dreamgiftFechaEntrega = new java.awt.TextField();
        dreamgiftHoraEnt = new java.awt.TextField();
        dreamgiftDireccionEnt = new java.awt.TextField();
        dreamgiftSaludo = new java.awt.TextField();
        dreamgiftApellido = new java.awt.TextField();
        dreamgiftComunaEnt = new java.awt.TextField();
        dreamgiftModificar = new javax.swing.JButton();
        dreamgiftBuscar = new javax.swing.JButton();
        dreamgiftPacks = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        dreamgiftTelefonoDest1 = new java.awt.TextField();
        dreamgiftComuna = new javax.swing.JComboBox<>();
        dreamgiftBanco = new javax.swing.JComboBox<>();
        dreamgiftCelular1 = new java.awt.TextField();
        dreamgiftIngresar1 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        superAdmProveedores = new javax.swing.JPanel();
        ProveeEstado = new javax.swing.JComboBox<>();
        ProveeRazonSoc = new javax.swing.JTextField();
        ProveeRut = new javax.swing.JTextField();
        ProveeDireccion = new javax.swing.JTextField();
        ProveeTelefono = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        ProveeGuardarBtn = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        ProveeMail = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        ProveeComuna = new javax.swing.JComboBox<>();
        ProveeModifBtn = new javax.swing.JButton();
        ProveeBuscar = new java.awt.TextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        ProveeNombContac = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        ProveeBuscarBtn = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        ProveeIdProv = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        proveeTabla1 = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        superAdmUsuarios = new javax.swing.JPanel();
        usuarioBuscarUser = new javax.swing.JTextField();
        usuariosGuardarBtn = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        usuariosContraseña = new javax.swing.JPasswordField();
        usuariosAgregarUserBtn = new javax.swing.JButton();
        usuariosBuscarUserBtn = new javax.swing.JButton();
        usuarioNombreUser1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        dreamgiftventasPend1 = new javax.swing.JList<>();
        usuariosModifUserBtn1 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        superAdmBancos = new javax.swing.JPanel();
        bcoBuscar = new javax.swing.JTextField();
        bcoGuardarBtn = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        bcoAgregarBcoBtn = new javax.swing.JButton();
        bcoBuscarBtn = new javax.swing.JButton();
        bcoCodigo = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        bcoListado = new javax.swing.JList<>();
        bcoModifBtn = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        bcoDescripcion1 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        superAdmlClientes = new javax.swing.JPanel();
        clientesEstado = new javax.swing.JComboBox<>();
        clientesNombre = new javax.swing.JTextField();
        clientesRut = new javax.swing.JTextField();
        clientesFechNac = new javax.swing.JTextField();
        clientesDireccion = new javax.swing.JTextField();
        clientesTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clientesGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        clientesApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clientesBanco = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        clientesMail = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        clientesComuna = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        clientesCelular = new javax.swing.JTextField();
        clientesModificar = new javax.swing.JButton();
        clientesBuscar = new java.awt.TextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        clientesBuscarBtn = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        superAdmRrss = new javax.swing.JPanel();
        superAdmPacks = new javax.swing.JPanel();
        superAdmArticulos = new javax.swing.JPanel();
        jPanelComunas = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        superAdmPestañas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        superAdmPestañas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        superAdmIngresoVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        superAdmIngresoVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        superAdmIngresoVenta.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre");
        superAdmIngresoVenta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rut");
        superAdmIngresoVenta.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Direccion");
        superAdmIngresoVenta.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Comuna");
        superAdmIngresoVenta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Banco");
        superAdmIngresoVenta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ingreso Venta");
        superAdmIngresoVenta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        dreamgiftTelefono.setName(""); // NOI18N
        dreamgiftTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftTelefonoActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total");
        superAdmIngresoVenta.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ventas Pendientes");
        superAdmIngresoVenta.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Telefono");
        superAdmIngresoVenta.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("RRSS");
        superAdmIngresoVenta.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Mail");
        superAdmIngresoVenta.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fecha Nac.");
        superAdmIngresoVenta.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Telefono");
        superAdmIngresoVenta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Celular");
        superAdmIngresoVenta.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Fecha Entrega");
        superAdmIngresoVenta.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Direccion Entrega");
        superAdmIngresoVenta.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Destinatario");
        superAdmIngresoVenta.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Comuna Entrega");
        superAdmIngresoVenta.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Numero Pedido");
        superAdmIngresoVenta.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Hora Entrega");
        superAdmIngresoVenta.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Saludo");
        superAdmIngresoVenta.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        dreamgiftTotal.setName(""); // NOI18N
        dreamgiftTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftTotalActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        dreamgiftNumeroPedido.setName(""); // NOI18N
        dreamgiftNumeroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNumeroPedidoActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftNumeroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        dreamgiftBusquedaRut.setName(""); // NOI18N
        dreamgiftBusquedaRut.setText("12345678-9");
        dreamgiftBusquedaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBusquedaRutActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftBusquedaRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        dreamgiftRut.setName(""); // NOI18N
        dreamgiftRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftRutActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 230, -1));

        dreamgiftDireccion.setName(""); // NOI18N
        dreamgiftDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftDireccionActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, -1));

        dreamgiftMail.setName(""); // NOI18N
        dreamgiftMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftMailActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 230, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Seleccion de Pack");
        superAdmIngresoVenta.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        dreamgiftventasPend.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item6", "Item7", "Item8", "Item9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dreamgiftventasPend);

        superAdmIngresoVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, 120));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Apellido");
        superAdmIngresoVenta.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        dreamgiftNombre.setName(""); // NOI18N
        dreamgiftNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNombreActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 230, -1));

        dreamgiftRrss.setName(""); // NOI18N
        dreamgiftRrss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftRrssActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftRrss, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 220, -1));

        dreamgiftFechaNac.setName(""); // NOI18N
        dreamgiftFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftFechaNacActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, -1));

        dreamgiftDestinat.setName(""); // NOI18N
        dreamgiftDestinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftDestinatActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftDestinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 220, -1));

        dreamgiftFechaEntrega.setName(""); // NOI18N
        dreamgiftFechaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftFechaEntregaActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 110, -1));

        dreamgiftHoraEnt.setName(""); // NOI18N
        dreamgiftHoraEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftHoraEntActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftHoraEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 220, -1));

        dreamgiftDireccionEnt.setName(""); // NOI18N
        dreamgiftDireccionEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftDireccionEntActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftDireccionEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, -1));

        dreamgiftSaludo.setName(""); // NOI18N
        dreamgiftSaludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftSaludoActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 480, 40));

        dreamgiftApellido.setName(""); // NOI18N
        dreamgiftApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftApellidoActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 220, -1));

        dreamgiftComunaEnt.setName(""); // NOI18N
        dreamgiftComunaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftComunaEntActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftComunaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 220, -1));

        dreamgiftModificar.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftModificar.setText("Modificar");
        dreamgiftModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftModificarActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 104, 30));

        dreamgiftBuscar.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dreamgiftBuscar.setText("Buscar");
        dreamgiftBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBuscarActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        dreamgiftPacks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aniversario  $19.990", "Cumpleaños   $21.990", "Navidad   $25.990", "Matrimonio   $35.990" }));
        superAdmIngresoVenta.add(dreamgiftPacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText(" Ingrese Rut");
        superAdmIngresoVenta.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        dreamgiftTelefonoDest1.setName(""); // NOI18N
        dreamgiftTelefonoDest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftTelefonoDest1ActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftTelefonoDest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 220, -1));

        dreamgiftComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pudahuel", "Santiago", "Providencia", "" }));
        superAdmIngresoVenta.add(dreamgiftComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, -1));

        dreamgiftBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco Chile", "Santander" }));
        superAdmIngresoVenta.add(dreamgiftBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, -1));

        dreamgiftCelular1.setName(""); // NOI18N
        dreamgiftCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftCelular1ActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 220, -1));

        dreamgiftIngresar1.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftIngresar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftIngresar1.setText("Ingresar");
        dreamgiftIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftIngresar1ActionPerformed(evt);
            }
        });
        superAdmIngresoVenta.add(dreamgiftIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 104, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 4, 4));
        jLabel47.setText("(12345678-9)");
        superAdmIngresoVenta.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmIngresoVenta.add(jDesktopPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 570));

        superAdmPestañas.addTab("Ingreso Venta", superAdmIngresoVenta);

        superAdmProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProveeEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ProveeEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        ProveeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeEstadoActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 260, 160, -1));

        ProveeRazonSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeRazonSocActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeRazonSoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 162, -1));
        superAdmProveedores.add(ProveeRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 162, -1));
        superAdmProveedores.add(ProveeDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 162, -1));
        superAdmProveedores.add(ProveeTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 162, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Estado");
        superAdmProveedores.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 50, -1));

        ProveeGuardarBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ProveeGuardarBtn.setText("Guardar");
        superAdmProveedores.add(ProveeGuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Telefono");
        superAdmProveedores.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Razon Social");
        superAdmProveedores.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("    Rut");
        superAdmProveedores.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 50, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("  Direccion");
        superAdmProveedores.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Administracion Proveedores");
        superAdmProveedores.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Mail");
        superAdmProveedores.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        ProveeMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeMailActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 162, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Comuna");
        superAdmProveedores.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        ProveeComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        superAdmProveedores.add(ProveeComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 160, -1));

        ProveeModifBtn.setBackground(new java.awt.Color(167, 196, 182));
        ProveeModifBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProveeModifBtn.setText("Modificar");
        ProveeModifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeModifBtnActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeModifBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 104, 30));

        ProveeBuscar.setName(""); // NOI18N
        ProveeBuscar.setText("76345678-9");
        ProveeBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeBuscarActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText(" Ingrese Rut");
        superAdmProveedores.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 4, 4));
        jLabel54.setText("(76345678-9)");
        superAdmProveedores.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        ProveeNombContac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeNombContacActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeNombContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 162, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Nombre Contacto");
        superAdmProveedores.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 120, -1));

        ProveeBuscarBtn.setBackground(new java.awt.Color(167, 196, 182));
        ProveeBuscarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ProveeBuscarBtn.setText("Buscar");
        ProveeBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeBuscarBtnActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeBuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 20));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Id");
        superAdmProveedores.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        ProveeIdProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveeIdProvActionPerformed(evt);
            }
        });
        superAdmProveedores.add(ProveeIdProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 162, -1));

        proveeTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Razon Social", "Rut", "Telefono", "Direccion", "Comuna", "Nombre Contacto", "Mail", "Estado"
            }
        ));
        jScrollPane3.setViewportView(proveeTabla1);
        if (proveeTabla1.getColumnModel().getColumnCount() > 0) {
            proveeTabla1.getColumnModel().getColumn(1).setResizable(false);
            proveeTabla1.getColumnModel().getColumn(4).setResizable(false);
            proveeTabla1.getColumnModel().getColumn(6).setResizable(false);
        }

        superAdmProveedores.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 700, 120));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmProveedores.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 570));

        superAdmPestañas.addTab("Proveedores", superAdmProveedores);

        superAdmUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioBuscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBuscarUserActionPerformed(evt);
            }
        });
        superAdmUsuarios.add(usuarioBuscarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 162, -1));

        usuariosGuardarBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        usuariosGuardarBtn.setText("Guardar");
        superAdmUsuarios.add(usuariosGuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Administracion Usuarios");
        superAdmUsuarios.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Busqueda de Usuario");
        superAdmUsuarios.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Contraseña");
        superAdmUsuarios.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        usuariosContraseña.setText("jPasswordField1");
        superAdmUsuarios.add(usuariosContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 160, -1));

        usuariosAgregarUserBtn.setBackground(new java.awt.Color(167, 196, 182));
        usuariosAgregarUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuariosAgregarUserBtn.setText("Agregar");
        usuariosAgregarUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosAgregarUserBtnActionPerformed(evt);
            }
        });
        superAdmUsuarios.add(usuariosAgregarUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 104, 30));

        usuariosBuscarUserBtn.setBackground(new java.awt.Color(167, 196, 182));
        usuariosBuscarUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuariosBuscarUserBtn.setText("Buscar");
        usuariosBuscarUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosBuscarUserBtnActionPerformed(evt);
            }
        });
        superAdmUsuarios.add(usuariosBuscarUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 80, 20));

        usuarioNombreUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioNombreUser1ActionPerformed(evt);
            }
        });
        superAdmUsuarios.add(usuarioNombreUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 162, -1));

        dreamgiftventasPend1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item6", "Item7", "Item8", "Item9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        dreamgiftventasPend1.setToolTipText("");
        jScrollPane5.setViewportView(dreamgiftventasPend1);

        superAdmUsuarios.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 380, 120));

        usuariosModifUserBtn1.setBackground(new java.awt.Color(167, 196, 182));
        usuariosModifUserBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuariosModifUserBtn1.setText("Modificar");
        usuariosModifUserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosModifUserBtn1ActionPerformed(evt);
            }
        });
        superAdmUsuarios.add(usuariosModifUserBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 104, 30));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Nombre Usuario");
        superAdmUsuarios.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmUsuarios.add(jDesktopPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));

        superAdmPestañas.addTab("Usuarios", superAdmUsuarios);

        superAdmBancos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bcoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoBuscarActionPerformed(evt);
            }
        });
        superAdmBancos.add(bcoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 162, -1));

        bcoGuardarBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bcoGuardarBtn.setText("Guardar");
        superAdmBancos.add(bcoGuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Administracion Bancos");
        superAdmBancos.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Busqueda de Usuario");
        superAdmBancos.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Codigo");
        superAdmBancos.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        bcoAgregarBcoBtn.setBackground(new java.awt.Color(167, 196, 182));
        bcoAgregarBcoBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcoAgregarBcoBtn.setText("Agregar");
        bcoAgregarBcoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoAgregarBcoBtnActionPerformed(evt);
            }
        });
        superAdmBancos.add(bcoAgregarBcoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 104, 30));

        bcoBuscarBtn.setBackground(new java.awt.Color(167, 196, 182));
        bcoBuscarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcoBuscarBtn.setText("Buscar");
        bcoBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoBuscarBtnActionPerformed(evt);
            }
        });
        superAdmBancos.add(bcoBuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 80, 20));

        bcoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoCodigoActionPerformed(evt);
            }
        });
        superAdmBancos.add(bcoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 162, -1));

        bcoListado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item6", "Item7", "Item8", "Item9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bcoListado.setToolTipText("");
        jScrollPane6.setViewportView(bcoListado);

        superAdmBancos.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 380, 120));

        bcoModifBtn.setBackground(new java.awt.Color(167, 196, 182));
        bcoModifBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bcoModifBtn.setText("Modificar");
        bcoModifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoModifBtnActionPerformed(evt);
            }
        });
        superAdmBancos.add(bcoModifBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 104, 30));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Descripcion");
        superAdmBancos.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        bcoDescripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoDescripcion1ActionPerformed(evt);
            }
        });
        superAdmBancos.add(bcoDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 162, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmBancos.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));

        superAdmPestañas.addTab("Bancos", superAdmBancos);

        superAdmlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientesEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clientesEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        superAdmlClientes.add(clientesEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 181, -1));

        clientesNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesNombreActionPerformed(evt);
            }
        });
        superAdmlClientes.add(clientesNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 162, -1));
        superAdmlClientes.add(clientesRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 162, -1));
        superAdmlClientes.add(clientesFechNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 162, -1));
        superAdmlClientes.add(clientesDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 162, -1));
        superAdmlClientes.add(clientesTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 162, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado");
        superAdmlClientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 50, -1));

        clientesGuardar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clientesGuardar.setText("Guardar");
        superAdmlClientes.add(clientesGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefono");
        superAdmlClientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        superAdmlClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("    Rut");
        superAdmlClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Nacimiento");
        superAdmlClientes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Direccion");
        superAdmlClientes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Banco");
        superAdmlClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Administracion Clientes");
        superAdmlClientes.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        clientesApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesApellidoActionPerformed(evt);
            }
        });
        superAdmlClientes.add(clientesApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 162, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellido");
        superAdmlClientes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        clientesBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        superAdmlClientes.add(clientesBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 160, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Mail");
        superAdmlClientes.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        clientesMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMailActionPerformed(evt);
            }
        });
        superAdmlClientes.add(clientesMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 162, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Comuna");
        superAdmlClientes.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        clientesComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        superAdmlClientes.add(clientesComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Celular");
        superAdmlClientes.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));
        superAdmlClientes.add(clientesCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 162, -1));

        clientesModificar.setBackground(new java.awt.Color(167, 196, 182));
        clientesModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientesModificar.setText("Modificar");
        clientesModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesModificarActionPerformed(evt);
            }
        });
        superAdmlClientes.add(clientesModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 104, 30));

        clientesBuscar.setName(""); // NOI18N
        clientesBuscar.setText("12345678-9");
        clientesBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBuscarActionPerformed(evt);
            }
        });
        superAdmlClientes.add(clientesBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 90, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" Ingrese Rut");
        superAdmlClientes.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 4, 4));
        jLabel40.setText("(12345678-9)");
        superAdmlClientes.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        clientesBuscarBtn.setBackground(new java.awt.Color(167, 196, 182));
        clientesBuscarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clientesBuscarBtn.setText("Buscar");
        clientesBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBuscarBtnActionPerformed(evt);
            }
        });
        superAdmlClientes.add(clientesBuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, 20));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmlClientes.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 570));

        superAdmPestañas.addTab("Clientes", superAdmlClientes);

        javax.swing.GroupLayout superAdmRrssLayout = new javax.swing.GroupLayout(superAdmRrss);
        superAdmRrss.setLayout(superAdmRrssLayout);
        superAdmRrssLayout.setHorizontalGroup(
            superAdmRrssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        superAdmRrssLayout.setVerticalGroup(
            superAdmRrssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmPestañas.addTab("Rrss", superAdmRrss);

        javax.swing.GroupLayout superAdmPacksLayout = new javax.swing.GroupLayout(superAdmPacks);
        superAdmPacks.setLayout(superAdmPacksLayout);
        superAdmPacksLayout.setHorizontalGroup(
            superAdmPacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        superAdmPacksLayout.setVerticalGroup(
            superAdmPacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmPestañas.addTab("Packs", superAdmPacks);

        javax.swing.GroupLayout superAdmArticulosLayout = new javax.swing.GroupLayout(superAdmArticulos);
        superAdmArticulos.setLayout(superAdmArticulosLayout);
        superAdmArticulosLayout.setHorizontalGroup(
            superAdmArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        superAdmArticulosLayout.setVerticalGroup(
            superAdmArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        superAdmPestañas.addTab("Articulos", superAdmArticulos);

        jPanelComunas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelComunasLayout = new javax.swing.GroupLayout(jPanelComunas);
        jPanelComunas.setLayout(jPanelComunasLayout);
        jPanelComunasLayout.setHorizontalGroup(
            jPanelComunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        jPanelComunasLayout.setVerticalGroup(
            jPanelComunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        superAdmPestañas.addTab("BORRAR*Comunas", jPanelComunas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(superAdmPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(superAdmPestañas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void usuariosModifUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosModifUserBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariosModifUserBtn1ActionPerformed

    private void usuarioNombreUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioNombreUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioNombreUser1ActionPerformed

    private void usuariosBuscarUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosBuscarUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariosBuscarUserBtnActionPerformed

    private void usuariosAgregarUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosAgregarUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariosAgregarUserBtnActionPerformed

    private void usuarioBuscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBuscarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioBuscarUserActionPerformed

    private void ProveeIdProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeIdProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeIdProvActionPerformed

    private void ProveeBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeBuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeBuscarBtnActionPerformed

    private void ProveeNombContacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeNombContacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeNombContacActionPerformed

    private void ProveeBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeBuscarActionPerformed

    private void ProveeModifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeModifBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeModifBtnActionPerformed

    private void ProveeMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeMailActionPerformed

    private void ProveeRazonSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeRazonSocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeRazonSocActionPerformed

    private void ProveeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveeEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveeEstadoActionPerformed

    private void clientesBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesBuscarBtnActionPerformed

    private void clientesBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesBuscarActionPerformed

    private void clientesModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesModificarActionPerformed

    private void clientesMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesMailActionPerformed

    private void clientesApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesApellidoActionPerformed

    private void clientesNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesNombreActionPerformed

    private void dreamgiftIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftIngresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftIngresar1ActionPerformed

    private void dreamgiftCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftCelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftCelular1ActionPerformed

    private void dreamgiftTelefonoDest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftTelefonoDest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftTelefonoDest1ActionPerformed

    private void dreamgiftBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBuscarActionPerformed

    private void dreamgiftModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftModificarActionPerformed

    private void dreamgiftComunaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftComunaEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftComunaEntActionPerformed

    private void dreamgiftApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftApellidoActionPerformed

    private void dreamgiftSaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftSaludoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftSaludoActionPerformed

    private void dreamgiftDireccionEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftDireccionEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftDireccionEntActionPerformed

    private void dreamgiftHoraEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftHoraEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftHoraEntActionPerformed

    private void dreamgiftFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftFechaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftFechaEntregaActionPerformed

    private void dreamgiftDestinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftDestinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftDestinatActionPerformed

    private void dreamgiftFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftFechaNacActionPerformed

    private void dreamgiftRrssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftRrssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftRrssActionPerformed

    private void dreamgiftNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNombreActionPerformed

    private void dreamgiftMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftMailActionPerformed

    private void dreamgiftDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftDireccionActionPerformed

    private void dreamgiftRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftRutActionPerformed

    private void dreamgiftBusquedaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBusquedaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBusquedaRutActionPerformed

    private void dreamgiftNumeroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNumeroPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNumeroPedidoActionPerformed

    private void dreamgiftTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftTotalActionPerformed

    private void dreamgiftTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftTelefonoActionPerformed

    private void bcoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcoBuscarActionPerformed

    private void bcoAgregarBcoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoAgregarBcoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcoAgregarBcoBtnActionPerformed

    private void bcoBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoBuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcoBuscarBtnActionPerformed

    private void bcoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcoCodigoActionPerformed

    private void bcoModifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoModifBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcoModifBtnActionPerformed

    private void bcoDescripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoDescripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcoDescripcion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.TextField ProveeBuscar;
    public javax.swing.JButton ProveeBuscarBtn;
    public javax.swing.JComboBox<String> ProveeComuna;
    public javax.swing.JTextField ProveeDireccion;
    public javax.swing.JComboBox<String> ProveeEstado;
    public javax.swing.JButton ProveeGuardarBtn;
    public javax.swing.JTextField ProveeIdProv;
    public javax.swing.JTextField ProveeMail;
    public javax.swing.JButton ProveeModifBtn;
    public javax.swing.JTextField ProveeNombContac;
    public javax.swing.JTextField ProveeRazonSoc;
    public javax.swing.JTextField ProveeRut;
    public javax.swing.JTextField ProveeTelefono;
    public javax.swing.JButton bcoAgregarBcoBtn;
    public javax.swing.JTextField bcoBuscar;
    public javax.swing.JButton bcoBuscarBtn;
    public javax.swing.JTextField bcoCodigo;
    public javax.swing.JTextField bcoDescripcion1;
    public javax.swing.JButton bcoGuardarBtn;
    public javax.swing.JList<String> bcoListado;
    public javax.swing.JButton bcoModifBtn;
    public javax.swing.JTextField clientesApellido;
    public javax.swing.JComboBox<String> clientesBanco;
    public java.awt.TextField clientesBuscar;
    public javax.swing.JButton clientesBuscarBtn;
    public javax.swing.JTextField clientesCelular;
    public javax.swing.JComboBox<String> clientesComuna;
    public javax.swing.JTextField clientesDireccion;
    public javax.swing.JComboBox<String> clientesEstado;
    public javax.swing.JTextField clientesFechNac;
    public javax.swing.JButton clientesGuardar;
    public javax.swing.JTextField clientesMail;
    public javax.swing.JButton clientesModificar;
    public javax.swing.JTextField clientesNombre;
    public javax.swing.JTextField clientesRut;
    public javax.swing.JTextField clientesTelefono;
    public java.awt.TextField dreamgiftApellido;
    public javax.swing.JComboBox<String> dreamgiftBanco;
    public javax.swing.JButton dreamgiftBuscar;
    public java.awt.TextField dreamgiftBusquedaRut;
    public java.awt.TextField dreamgiftCelular1;
    public javax.swing.JComboBox<String> dreamgiftComuna;
    public java.awt.TextField dreamgiftComunaEnt;
    public java.awt.TextField dreamgiftDestinat;
    public java.awt.TextField dreamgiftDireccion;
    public java.awt.TextField dreamgiftDireccionEnt;
    public java.awt.TextField dreamgiftFechaEntrega;
    public java.awt.TextField dreamgiftFechaNac;
    public java.awt.TextField dreamgiftHoraEnt;
    public javax.swing.JButton dreamgiftIngresar1;
    public java.awt.TextField dreamgiftMail;
    public javax.swing.JButton dreamgiftModificar;
    public java.awt.TextField dreamgiftNombre;
    public java.awt.TextField dreamgiftNumeroPedido;
    public javax.swing.JComboBox<String> dreamgiftPacks;
    public java.awt.TextField dreamgiftRrss;
    public java.awt.TextField dreamgiftRut;
    public java.awt.TextField dreamgiftSaludo;
    public java.awt.TextField dreamgiftTelefono;
    public java.awt.TextField dreamgiftTelefonoDest1;
    public java.awt.TextField dreamgiftTotal;
    public javax.swing.JList<String> dreamgiftventasPend;
    public javax.swing.JList<String> dreamgiftventasPend1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel60;
    public javax.swing.JLabel jLabel62;
    public javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelComunas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTable proveeTabla1;
    private javax.swing.JPanel superAdmArticulos;
    private javax.swing.JPanel superAdmBancos;
    private javax.swing.JPanel superAdmIngresoVenta;
    private javax.swing.JPanel superAdmPacks;
    public javax.swing.JTabbedPane superAdmPestañas;
    private javax.swing.JPanel superAdmProveedores;
    private javax.swing.JPanel superAdmRrss;
    private javax.swing.JPanel superAdmUsuarios;
    private javax.swing.JPanel superAdmlClientes;
    public javax.swing.JTextField usuarioBuscarUser;
    public javax.swing.JTextField usuarioNombreUser1;
    public javax.swing.JButton usuariosAgregarUserBtn;
    public javax.swing.JButton usuariosBuscarUserBtn;
    private javax.swing.JPasswordField usuariosContraseña;
    public javax.swing.JButton usuariosGuardarBtn;
    public javax.swing.JButton usuariosModifUserBtn1;
    // End of variables declaration//GEN-END:variables
}
