/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author usuario
 */
public class SuperAdm extends javax.swing.JFrame {

    /**
     * Creates new form MenuPpal
     */
    public SuperAdm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dreamgiftPestañas = new javax.swing.JTabbedPane();
        dreamgiftIngresoVenta = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dreamgiftTelefono = new java.awt.TextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dreamgiftTotal = new java.awt.TextField();
        dreamgiftNumeroPedido = new java.awt.TextField();
        dreamgiftBusquedaRut = new java.awt.TextField();
        dreamgiftRut = new java.awt.TextField();
        dreamgiftDireccion = new java.awt.TextField();
        dreamgiftMail = new java.awt.TextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dreamgiftventasPend = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        dreamgiftNombre = new java.awt.TextField();
        dreamgiftRrss = new java.awt.TextField();
        dreamgiftFechaNac = new java.awt.TextField();
        dreamgiftDestinat = new java.awt.TextField();
        dreamgiftFechaEntrega = new java.awt.TextField();
        dreamgiftHoraEnt = new java.awt.TextField();
        dreamgiftDireccionEnt = new java.awt.TextField();
        dreamgiftSaludo = new java.awt.TextField();
        dreamgiftApellido = new java.awt.TextField();
        dreamgiftComunaEnt = new java.awt.TextField();
        dreamgiftModificar = new javax.swing.JButton();
        dreamgiftBuscar = new javax.swing.JButton();
        dreamgiftPacks = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        dreamgiftTelefonoDest1 = new java.awt.TextField();
        dreamgiftComuna = new javax.swing.JComboBox<>();
        dreamgiftBanco = new javax.swing.JComboBox<>();
        dreamgiftCelular1 = new java.awt.TextField();
        dreamgiftIngresar1 = new javax.swing.JButton();
        dreamgiftlClientes = new javax.swing.JPanel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        dreamgiftNombreCompleto = new javax.swing.JTextField();
        jTextFieldRut = new javax.swing.JTextField();
        jTextFieldCumpleaños = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1Guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldNombreCompleto1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldNombreCompleto2 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldTelefono1 = new javax.swing.JTextField();
        dreamgiftModificar1 = new javax.swing.JButton();
        dreamgiftBusquedaRut3 = new java.awt.TextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        dreamgiftBuscarCli = new javax.swing.JButton();
        dreamgiftProveedores = new javax.swing.JPanel();
        dreamgiftEstadoProv = new javax.swing.JComboBox<>();
        dreamgiftRazonSoc = new javax.swing.JTextField();
        dreamgiftRutProv = new javax.swing.JTextField();
        dreamgiftDireccionProv = new javax.swing.JTextField();
        dreamgiftTelefonoProv = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jButton1GuardarProvBtn = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        dreamgiftMailProv = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        dreamgiftComunaProv = new javax.swing.JComboBox<>();
        dreamgiftModifProvBtn = new javax.swing.JButton();
        dreamgiftBusquedaRutProv = new java.awt.TextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        dreamgiftNombCtcProv = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        dreamgiftBuscarProvBtn = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        dreamgiftIDProv = new javax.swing.JTextField();
        dreamgiftUsuarios = new javax.swing.JPanel();
        dreamgiftEstadoUser = new javax.swing.JComboBox<>();
        dreamgiftUsuario = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jButton1GuardUserBtn = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        dreamgiftresetContraBtn = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        dreamgiftContraseñaUser = new javax.swing.JPasswordField();
        dreamgiftAgregarUserBtn = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        dreamgiftModificarUserBtn = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        dreamgiftNombreUser = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        dreamgiftApellidoUser = new javax.swing.JTextField();
        dreamgiftBancos = new javax.swing.JPanel();
        dreamgiftEstadoProv1 = new javax.swing.JComboBox<>();
        dreamgiftBanco1 = new javax.swing.JTextField();
        dreamgiftRutProv1az = new javax.swing.JTextField();
        dreamgiftDireccionProv1 = new javax.swing.JTextField();
        dreamgiftTelefonoProv1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jButton1GuardarProvBtn1 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        dreamgiftBancoProv1 = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        dreamgiftMailProv1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        dreamgiftComunaProv1 = new javax.swing.JComboBox<>();
        dreamgiftModifProvBtn1 = new javax.swing.JButton();
        dreamgiftBusquedaRutProv1 = new java.awt.TextField();
        dreamgiftNombCtcProv1 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        dreamgiftBuscarProvBtn1 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        dreamgiftIdBco = new javax.swing.JTextField();
        dreamgiftRrssPestaña = new javax.swing.JPanel();
        dreamgiftPacksPestaña = new javax.swing.JPanel();
        dreamgiftArticulos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelComunas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dreamgiftPestañas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dreamgiftPestañas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        dreamgiftIngresoVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dreamgiftIngresoVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 4, 4));
        jLabel9.setText("(12345678-9)");
        dreamgiftIngresoVenta.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));
        dreamgiftIngresoVenta.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Nombre");
        dreamgiftIngresoVenta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Rut");
        dreamgiftIngresoVenta.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Direccion");
        dreamgiftIngresoVenta.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Comuna");
        dreamgiftIngresoVenta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Banco");
        dreamgiftIngresoVenta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Ingreso Venta");
        dreamgiftIngresoVenta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        dreamgiftTelefono.setName(""); // NOI18N
        dreamgiftTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftTelefonoActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 230, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Total");
        dreamgiftIngresoVenta.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Ventas Pendientes");
        dreamgiftIngresoVenta.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Telefono");
        dreamgiftIngresoVenta.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("RRSS");
        dreamgiftIngresoVenta.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Mail");
        dreamgiftIngresoVenta.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Fecha Nac.");
        dreamgiftIngresoVenta.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Telefono");
        dreamgiftIngresoVenta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Celular");
        dreamgiftIngresoVenta.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Fecha Entrega");
        dreamgiftIngresoVenta.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Direccion Entrega");
        dreamgiftIngresoVenta.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Destinatario");
        dreamgiftIngresoVenta.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Comuna Entrega");
        dreamgiftIngresoVenta.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Numero Pedido");
        dreamgiftIngresoVenta.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Hora Entrega");
        dreamgiftIngresoVenta.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Saludo");
        dreamgiftIngresoVenta.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        dreamgiftTotal.setName(""); // NOI18N
        dreamgiftTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftTotalActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, -1));

        dreamgiftNumeroPedido.setName(""); // NOI18N
        dreamgiftNumeroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNumeroPedidoActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftNumeroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        dreamgiftBusquedaRut.setName(""); // NOI18N
        dreamgiftBusquedaRut.setText("12345678-9");
        dreamgiftBusquedaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBusquedaRutActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftBusquedaRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        dreamgiftRut.setName(""); // NOI18N
        dreamgiftRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftRutActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 230, -1));

        dreamgiftDireccion.setName(""); // NOI18N
        dreamgiftDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftDireccionActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 230, -1));

        dreamgiftMail.setName(""); // NOI18N
        dreamgiftMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftMailActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 230, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Seleccion de Pack");
        dreamgiftIngresoVenta.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        dreamgiftventasPend.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item6", "Item7", "Item8", "Item9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dreamgiftventasPend);

        dreamgiftIngresoVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 160, 120));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Apellido");
        dreamgiftIngresoVenta.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        dreamgiftNombre.setName(""); // NOI18N
        dreamgiftNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNombreActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 230, -1));

        dreamgiftRrss.setName(""); // NOI18N
        dreamgiftRrss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftRrssActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftRrss, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 230, -1));

        dreamgiftFechaNac.setName(""); // NOI18N
        dreamgiftFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftFechaNacActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, -1));

        dreamgiftDestinat.setName(""); // NOI18N
        dreamgiftDestinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftDestinatActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftDestinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 230, -1));

        dreamgiftFechaEntrega.setName(""); // NOI18N
        dreamgiftFechaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftFechaEntregaActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 110, -1));

        dreamgiftHoraEnt.setName(""); // NOI18N
        dreamgiftHoraEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftHoraEntActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftHoraEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 230, -1));

        dreamgiftDireccionEnt.setName(""); // NOI18N
        dreamgiftDireccionEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftDireccionEntActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftDireccionEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 230, -1));

        dreamgiftSaludo.setName(""); // NOI18N
        dreamgiftSaludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftSaludoActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 510, -1));

        dreamgiftApellido.setName(""); // NOI18N
        dreamgiftApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftApellidoActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 230, -1));

        dreamgiftComunaEnt.setName(""); // NOI18N
        dreamgiftComunaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftComunaEntActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftComunaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 230, -1));

        dreamgiftModificar.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftModificar.setText("Modificar");
        dreamgiftModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftModificarActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 104, 30));

        dreamgiftBuscar.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dreamgiftBuscar.setText("Buscar");
        dreamgiftBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBuscarActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        dreamgiftPacks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aniversario  $19.990", "Cumpleaños   $21.990", "Navidad   $25.990", "Matrimonio   $35.990" }));
        dreamgiftIngresoVenta.add(dreamgiftPacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText(" Ingrese Rut");
        dreamgiftIngresoVenta.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        dreamgiftTelefonoDest1.setName(""); // NOI18N
        dreamgiftTelefonoDest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftTelefonoDest1ActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftTelefonoDest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 230, -1));

        dreamgiftComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pudahuel", "Santiago", "Providencia", "" }));
        dreamgiftIngresoVenta.add(dreamgiftComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 230, -1));

        dreamgiftBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco Chile", "Santander" }));
        dreamgiftIngresoVenta.add(dreamgiftBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 230, -1));

        dreamgiftCelular1.setName(""); // NOI18N
        dreamgiftCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftCelular1ActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 230, -1));

        dreamgiftIngresar1.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftIngresar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftIngresar1.setText("Ingresar");
        dreamgiftIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftIngresar1ActionPerformed(evt);
            }
        });
        dreamgiftIngresoVenta.add(dreamgiftIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 104, 30));

        dreamgiftPestañas.addTab("Ingreso Venta", dreamgiftIngresoVenta);

        dreamgiftlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        dreamgiftlClientes.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 181, -1));

        dreamgiftNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNombreCompletoActionPerformed(evt);
            }
        });
        dreamgiftlClientes.add(dreamgiftNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 162, -1));
        dreamgiftlClientes.add(jTextFieldRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 162, -1));
        dreamgiftlClientes.add(jTextFieldCumpleaños, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 162, -1));
        dreamgiftlClientes.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 162, -1));
        dreamgiftlClientes.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 162, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Estado");
        dreamgiftlClientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 50, -1));

        jButton1Guardar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1Guardar.setText("Guardar");
        dreamgiftlClientes.add(jButton1Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Telefono");
        dreamgiftlClientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");
        dreamgiftlClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("    Rut");
        dreamgiftlClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Fecha Nacimiento");
        dreamgiftlClientes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("  Direccion");
        dreamgiftlClientes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Banco");
        dreamgiftlClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Administracion Clientes");
        dreamgiftlClientes.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jTextFieldNombreCompleto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCompleto1ActionPerformed(evt);
            }
        });
        dreamgiftlClientes.add(jTextFieldNombreCompleto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 162, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Apellido");
        dreamgiftlClientes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dreamgiftlClientes.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 160, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Mail");
        dreamgiftlClientes.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jTextFieldNombreCompleto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCompleto2ActionPerformed(evt);
            }
        });
        dreamgiftlClientes.add(jTextFieldNombreCompleto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 162, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Comuna");
        dreamgiftlClientes.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dreamgiftlClientes.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Celular");
        dreamgiftlClientes.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));
        dreamgiftlClientes.add(jTextFieldTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 162, -1));

        dreamgiftModificar1.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftModificar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftModificar1.setText("Modificar");
        dreamgiftModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftModificar1ActionPerformed(evt);
            }
        });
        dreamgiftlClientes.add(dreamgiftModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 104, 30));

        dreamgiftBusquedaRut3.setName(""); // NOI18N
        dreamgiftBusquedaRut3.setText("12345678-9");
        dreamgiftBusquedaRut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBusquedaRut3ActionPerformed(evt);
            }
        });
        dreamgiftlClientes.add(dreamgiftBusquedaRut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setText(" Ingrese Rut");
        dreamgiftlClientes.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 4, 4));
        jLabel40.setText("(12345678-9)");
        dreamgiftlClientes.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        dreamgiftBuscarCli.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftBuscarCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dreamgiftBuscarCli.setText("Buscar");
        dreamgiftBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBuscarCliActionPerformed(evt);
            }
        });
        dreamgiftlClientes.add(dreamgiftBuscarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 20));

        dreamgiftPestañas.addTab("Clientes", dreamgiftlClientes);

        dreamgiftProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dreamgiftEstadoProv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dreamgiftEstadoProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        dreamgiftEstadoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftEstadoProvActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftEstadoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 181, -1));

        dreamgiftRazonSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftRazonSocActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftRazonSoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 162, -1));
        dreamgiftProveedores.add(dreamgiftRutProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 162, -1));
        dreamgiftProveedores.add(dreamgiftDireccionProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 162, -1));
        dreamgiftProveedores.add(dreamgiftTelefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 162, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("Estado");
        dreamgiftProveedores.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 50, -1));

        jButton1GuardarProvBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1GuardarProvBtn.setText("Guardar");
        dreamgiftProveedores.add(jButton1GuardarProvBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Telefono");
        dreamgiftProveedores.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("Razon Social");
        dreamgiftProveedores.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("    Rut");
        dreamgiftProveedores.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 40, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("  Direccion");
        dreamgiftProveedores.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setText("Administracion Proveedores");
        dreamgiftProveedores.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setText("Mail");
        dreamgiftProveedores.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        dreamgiftMailProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftMailProvActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftMailProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 162, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setText("Comuna");
        dreamgiftProveedores.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        dreamgiftComunaProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dreamgiftProveedores.add(dreamgiftComunaProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, -1));

        dreamgiftModifProvBtn.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftModifProvBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftModifProvBtn.setText("Modificar");
        dreamgiftModifProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftModifProvBtnActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftModifProvBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 104, 30));

        dreamgiftBusquedaRutProv.setName(""); // NOI18N
        dreamgiftBusquedaRutProv.setText("76345678-9");
        dreamgiftBusquedaRutProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBusquedaRutProvActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftBusquedaRutProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel53.setText(" Ingrese Rut");
        dreamgiftProveedores.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 4, 4));
        jLabel54.setText("(76345678-9)");
        dreamgiftProveedores.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        dreamgiftNombCtcProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNombCtcProvActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftNombCtcProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 162, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Nombre Contacto");
        dreamgiftProveedores.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        dreamgiftBuscarProvBtn.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftBuscarProvBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dreamgiftBuscarProvBtn.setText("Buscar");
        dreamgiftBuscarProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBuscarProvBtnActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftBuscarProvBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 20));

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel72.setText("Id");
        dreamgiftProveedores.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        dreamgiftIDProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftIDProvActionPerformed(evt);
            }
        });
        dreamgiftProveedores.add(dreamgiftIDProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 162, -1));

        dreamgiftPestañas.addTab("Proveedores", dreamgiftProveedores);

        dreamgiftUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dreamgiftEstadoUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dreamgiftEstadoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        dreamgiftEstadoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftEstadoUserActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftEstadoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 181, -1));

        dreamgiftUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftUsuarioActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 162, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setText("Estado");
        dreamgiftUsuarios.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, -1));

        jButton1GuardUserBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1GuardUserBtn.setText("Guardar");
        dreamgiftUsuarios.add(jButton1GuardUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setText("Nombre Usuario");
        dreamgiftUsuarios.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setText("Administracion Usuarios");
        dreamgiftUsuarios.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        dreamgiftresetContraBtn.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftresetContraBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftresetContraBtn.setText("Resetear Contraseña");
        dreamgiftresetContraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftresetContraBtnActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftresetContraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 180, 30));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setText("Busqueda de Usuario");
        dreamgiftUsuarios.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel64.setText("Contraseña");
        dreamgiftUsuarios.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        dreamgiftContraseñaUser.setText("jPasswordField1");
        dreamgiftUsuarios.add(dreamgiftContraseñaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, -1));

        dreamgiftAgregarUserBtn.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftAgregarUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftAgregarUserBtn.setText("Agregar");
        dreamgiftAgregarUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftAgregarUserBtnActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftAgregarUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 104, 30));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        dreamgiftModificarUserBtn.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftModificarUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftModificarUserBtn.setText("Modificar");
        dreamgiftModificarUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftModificarUserBtnActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftModificarUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 104, 30));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setText("Nombre");
        dreamgiftUsuarios.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        dreamgiftNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNombreUserActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 162, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel57.setText("Apellido");
        dreamgiftUsuarios.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        dreamgiftApellidoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftApellidoUserActionPerformed(evt);
            }
        });
        dreamgiftUsuarios.add(dreamgiftApellidoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 162, -1));

        dreamgiftPestañas.addTab("Usuarios", dreamgiftUsuarios);

        dreamgiftBancos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dreamgiftEstadoProv1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dreamgiftEstadoProv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        dreamgiftEstadoProv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftEstadoProv1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftEstadoProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 181, -1));

        dreamgiftBanco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBanco1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftBanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 162, -1));
        dreamgiftBancos.add(dreamgiftRutProv1az, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 162, -1));
        dreamgiftBancos.add(dreamgiftDireccionProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 162, -1));
        dreamgiftBancos.add(dreamgiftTelefonoProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 162, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setText("Estado");
        dreamgiftBancos.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 50, -1));

        jButton1GuardarProvBtn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1GuardarProvBtn1.setText("Guardar");
        dreamgiftBancos.add(jButton1GuardarProvBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel58.setText("Telefono");
        dreamgiftBancos.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel60.setText("Banco");
        dreamgiftBancos.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel61.setText("    Ruta");
        dreamgiftBancos.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel63.setText("  Direccion");
        dreamgiftBancos.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel65.setText("Banco");
        dreamgiftBancos.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setText("Administracion Bancos");
        dreamgiftBancos.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        dreamgiftBancoProv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dreamgiftBancos.add(dreamgiftBancoProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 160, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel67.setText("Mail");
        dreamgiftBancos.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        dreamgiftMailProv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftMailProv1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftMailProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 162, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel68.setText("Comuna");
        dreamgiftBancos.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        dreamgiftComunaProv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dreamgiftBancos.add(dreamgiftComunaProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, -1));

        dreamgiftModifProvBtn1.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftModifProvBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dreamgiftModifProvBtn1.setText("Modificar");
        dreamgiftModifProvBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftModifProvBtn1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftModifProvBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 104, 30));

        dreamgiftBusquedaRutProv1.setName(""); // NOI18N
        dreamgiftBusquedaRutProv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBusquedaRutProv1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftBusquedaRutProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, -1));

        dreamgiftNombCtcProv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftNombCtcProv1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftNombCtcProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 162, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel71.setText("Nombre Contacto");
        dreamgiftBancos.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        dreamgiftBuscarProvBtn1.setBackground(new java.awt.Color(167, 196, 182));
        dreamgiftBuscarProvBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dreamgiftBuscarProvBtn1.setText("Buscar");
        dreamgiftBuscarProvBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftBuscarProvBtn1ActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftBuscarProvBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 20));

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel73.setText("ID");
        dreamgiftBancos.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        dreamgiftIdBco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamgiftIdBcoActionPerformed(evt);
            }
        });
        dreamgiftBancos.add(dreamgiftIdBco, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 162, -1));

        dreamgiftPestañas.addTab("Bancos", dreamgiftBancos);

        javax.swing.GroupLayout dreamgiftRrssPestañaLayout = new javax.swing.GroupLayout(dreamgiftRrssPestaña);
        dreamgiftRrssPestaña.setLayout(dreamgiftRrssPestañaLayout);
        dreamgiftRrssPestañaLayout.setHorizontalGroup(
            dreamgiftRrssPestañaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        dreamgiftRrssPestañaLayout.setVerticalGroup(
            dreamgiftRrssPestañaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        dreamgiftPestañas.addTab("Rrss", dreamgiftRrssPestaña);

        javax.swing.GroupLayout dreamgiftPacksPestañaLayout = new javax.swing.GroupLayout(dreamgiftPacksPestaña);
        dreamgiftPacksPestaña.setLayout(dreamgiftPacksPestañaLayout);
        dreamgiftPacksPestañaLayout.setHorizontalGroup(
            dreamgiftPacksPestañaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        dreamgiftPacksPestañaLayout.setVerticalGroup(
            dreamgiftPacksPestañaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        dreamgiftPestañas.addTab("Packs", dreamgiftPacksPestaña);

        javax.swing.GroupLayout dreamgiftArticulosLayout = new javax.swing.GroupLayout(dreamgiftArticulos);
        dreamgiftArticulos.setLayout(dreamgiftArticulosLayout);
        dreamgiftArticulosLayout.setHorizontalGroup(
            dreamgiftArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        dreamgiftArticulosLayout.setVerticalGroup(
            dreamgiftArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        dreamgiftPestañas.addTab("Articulos", dreamgiftArticulos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        dreamgiftPestañas.addTab("tab10", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        dreamgiftPestañas.addTab("tab9", jPanel1);

        jPanelComunas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelComunasLayout = new javax.swing.GroupLayout(jPanelComunas);
        jPanelComunas.setLayout(jPanelComunasLayout);
        jPanelComunasLayout.setHorizontalGroup(
            jPanelComunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        jPanelComunasLayout.setVerticalGroup(
            jPanelComunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        dreamgiftPestañas.addTab("BORRAR*Comunas", jPanelComunas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dreamgiftPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dreamgiftPestañas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dreamgiftNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNombreCompletoActionPerformed

    private void dreamgiftTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftTelefonoActionPerformed

    private void dreamgiftTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftTotalActionPerformed

    private void dreamgiftNumeroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNumeroPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNumeroPedidoActionPerformed

    private void dreamgiftBusquedaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBusquedaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBusquedaRutActionPerformed

    private void dreamgiftRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftRutActionPerformed

    private void dreamgiftDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftDireccionActionPerformed

    private void dreamgiftMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftMailActionPerformed

    private void dreamgiftNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNombreActionPerformed

    private void dreamgiftRrssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftRrssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftRrssActionPerformed

    private void dreamgiftFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftFechaNacActionPerformed

    private void dreamgiftDestinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftDestinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftDestinatActionPerformed

    private void dreamgiftFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftFechaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftFechaEntregaActionPerformed

    private void dreamgiftHoraEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftHoraEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftHoraEntActionPerformed

    private void dreamgiftDireccionEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftDireccionEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftDireccionEntActionPerformed

    private void dreamgiftSaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftSaludoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftSaludoActionPerformed

    private void dreamgiftApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftApellidoActionPerformed

    private void dreamgiftComunaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftComunaEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftComunaEntActionPerformed

    private void dreamgiftModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftModificarActionPerformed

    private void dreamgiftBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBuscarActionPerformed

    private void dreamgiftTelefonoDest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftTelefonoDest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftTelefonoDest1ActionPerformed

    private void dreamgiftCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftCelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftCelular1ActionPerformed

    private void jTextFieldNombreCompleto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCompleto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCompleto1ActionPerformed

    private void jTextFieldNombreCompleto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCompleto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCompleto2ActionPerformed

    private void dreamgiftModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftModificar1ActionPerformed

    private void dreamgiftBusquedaRut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBusquedaRut3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBusquedaRut3ActionPerformed

    private void dreamgiftRazonSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftRazonSocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftRazonSocActionPerformed

    private void dreamgiftMailProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftMailProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftMailProvActionPerformed

    private void dreamgiftModifProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftModifProvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftModifProvBtnActionPerformed

    private void dreamgiftBusquedaRutProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBusquedaRutProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBusquedaRutProvActionPerformed

    private void dreamgiftEstadoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftEstadoProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftEstadoProvActionPerformed

    private void dreamgiftNombCtcProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNombCtcProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNombCtcProvActionPerformed

    private void dreamgiftEstadoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftEstadoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftEstadoUserActionPerformed

    private void dreamgiftUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftUsuarioActionPerformed

    private void dreamgiftresetContraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftresetContraBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftresetContraBtnActionPerformed

    private void dreamgiftAgregarUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftAgregarUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftAgregarUserBtnActionPerformed

    private void dreamgiftIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftIngresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftIngresar1ActionPerformed

    private void dreamgiftBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBuscarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBuscarCliActionPerformed

    private void dreamgiftBuscarProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBuscarProvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBuscarProvBtnActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void dreamgiftModificarUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftModificarUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftModificarUserBtnActionPerformed

    private void dreamgiftNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNombreUserActionPerformed

    private void dreamgiftApellidoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftApellidoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftApellidoUserActionPerformed

    private void dreamgiftEstadoProv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftEstadoProv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftEstadoProv1ActionPerformed

    private void dreamgiftBanco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBanco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBanco1ActionPerformed

    private void dreamgiftMailProv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftMailProv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftMailProv1ActionPerformed

    private void dreamgiftModifProvBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftModifProvBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftModifProvBtn1ActionPerformed

    private void dreamgiftBusquedaRutProv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBusquedaRutProv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBusquedaRutProv1ActionPerformed

    private void dreamgiftNombCtcProv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftNombCtcProv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftNombCtcProv1ActionPerformed

    private void dreamgiftBuscarProvBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftBuscarProvBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftBuscarProvBtn1ActionPerformed

    private void dreamgiftIDProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftIDProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftIDProvActionPerformed

    private void dreamgiftIdBcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamgiftIdBcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dreamgiftIdBcoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton dreamgiftAgregarUserBtn;
    public java.awt.TextField dreamgiftApellido;
    public javax.swing.JTextField dreamgiftApellidoUser;
    private javax.swing.JPanel dreamgiftArticulos;
    public javax.swing.JComboBox<String> dreamgiftBanco;
    public javax.swing.JTextField dreamgiftBanco1;
    public javax.swing.JComboBox<String> dreamgiftBancoProv1;
    private javax.swing.JPanel dreamgiftBancos;
    public javax.swing.JButton dreamgiftBuscar;
    public javax.swing.JButton dreamgiftBuscarCli;
    public javax.swing.JButton dreamgiftBuscarProvBtn;
    public javax.swing.JButton dreamgiftBuscarProvBtn1;
    public java.awt.TextField dreamgiftBusquedaRut;
    public java.awt.TextField dreamgiftBusquedaRut3;
    public java.awt.TextField dreamgiftBusquedaRutProv;
    public java.awt.TextField dreamgiftBusquedaRutProv1;
    public java.awt.TextField dreamgiftCelular1;
    public javax.swing.JComboBox<String> dreamgiftComuna;
    public java.awt.TextField dreamgiftComunaEnt;
    public javax.swing.JComboBox<String> dreamgiftComunaProv;
    public javax.swing.JComboBox<String> dreamgiftComunaProv1;
    private javax.swing.JPasswordField dreamgiftContraseñaUser;
    public java.awt.TextField dreamgiftDestinat;
    public java.awt.TextField dreamgiftDireccion;
    public java.awt.TextField dreamgiftDireccionEnt;
    public javax.swing.JTextField dreamgiftDireccionProv;
    public javax.swing.JTextField dreamgiftDireccionProv1;
    public javax.swing.JComboBox<String> dreamgiftEstadoProv;
    public javax.swing.JComboBox<String> dreamgiftEstadoProv1;
    public javax.swing.JComboBox<String> dreamgiftEstadoUser;
    public java.awt.TextField dreamgiftFechaEntrega;
    public java.awt.TextField dreamgiftFechaNac;
    public java.awt.TextField dreamgiftHoraEnt;
    public javax.swing.JTextField dreamgiftIDProv;
    public javax.swing.JTextField dreamgiftIdBco;
    public javax.swing.JButton dreamgiftIngresar1;
    private javax.swing.JPanel dreamgiftIngresoVenta;
    public java.awt.TextField dreamgiftMail;
    public javax.swing.JTextField dreamgiftMailProv;
    public javax.swing.JTextField dreamgiftMailProv1;
    public javax.swing.JButton dreamgiftModifProvBtn;
    public javax.swing.JButton dreamgiftModifProvBtn1;
    public javax.swing.JButton dreamgiftModificar;
    public javax.swing.JButton dreamgiftModificar1;
    public javax.swing.JButton dreamgiftModificarUserBtn;
    public javax.swing.JTextField dreamgiftNombCtcProv;
    public javax.swing.JTextField dreamgiftNombCtcProv1;
    public java.awt.TextField dreamgiftNombre;
    public javax.swing.JTextField dreamgiftNombreCompleto;
    public javax.swing.JTextField dreamgiftNombreUser;
    public java.awt.TextField dreamgiftNumeroPedido;
    public javax.swing.JComboBox<String> dreamgiftPacks;
    private javax.swing.JPanel dreamgiftPacksPestaña;
    public javax.swing.JTabbedPane dreamgiftPestañas;
    private javax.swing.JPanel dreamgiftProveedores;
    public javax.swing.JTextField dreamgiftRazonSoc;
    public java.awt.TextField dreamgiftRrss;
    private javax.swing.JPanel dreamgiftRrssPestaña;
    public java.awt.TextField dreamgiftRut;
    public javax.swing.JTextField dreamgiftRutProv;
    public javax.swing.JTextField dreamgiftRutProv1az;
    public java.awt.TextField dreamgiftSaludo;
    public java.awt.TextField dreamgiftTelefono;
    public java.awt.TextField dreamgiftTelefonoDest1;
    public javax.swing.JTextField dreamgiftTelefonoProv;
    public javax.swing.JTextField dreamgiftTelefonoProv1;
    public java.awt.TextField dreamgiftTotal;
    public javax.swing.JTextField dreamgiftUsuario;
    private javax.swing.JPanel dreamgiftUsuarios;
    private javax.swing.JPanel dreamgiftlClientes;
    public javax.swing.JButton dreamgiftresetContraBtn;
    public javax.swing.JList<String> dreamgiftventasPend;
    public javax.swing.JButton jButton1GuardUserBtn;
    public javax.swing.JButton jButton1Guardar;
    public javax.swing.JButton jButton1GuardarProvBtn;
    public javax.swing.JButton jButton1GuardarProvBtn1;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    public javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    public javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    public javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    public javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelComunas;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextFieldCumpleaños;
    public javax.swing.JTextField jTextFieldDireccion;
    public javax.swing.JTextField jTextFieldNombreCompleto1;
    public javax.swing.JTextField jTextFieldNombreCompleto2;
    public javax.swing.JTextField jTextFieldRut;
    public javax.swing.JTextField jTextFieldTelefono;
    public javax.swing.JTextField jTextFieldTelefono1;
    // End of variables declaration//GEN-END:variables
}
