/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Roberto
 */
public class venta extends javax.swing.JFrame {

    /**
     * Creates new form venta
     */
    public venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventaPestañas = new javax.swing.JTabbedPane();
        iVenta = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        iVentaTelefono = new java.awt.TextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        iVentaTotal = new java.awt.TextField();
        iVentaNumeroPedido = new java.awt.TextField();
        iVentaBusquedaRut = new java.awt.TextField();
        iVentaRut = new java.awt.TextField();
        iVentaMail = new java.awt.TextField();
        jLabel32 = new javax.swing.JLabel();
        iVentaVentasPendList = new javax.swing.JScrollPane();
        iVentaventasPendList = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        iVentaNombre = new java.awt.TextField();
        iVentaRrss = new java.awt.TextField();
        iVentaFechaNac = new java.awt.TextField();
        iVentaDestinat = new java.awt.TextField();
        iVentaFechaEntrega = new java.awt.TextField();
        iVentaHoraEnt = new java.awt.TextField();
        iVentaDireccionEnt = new java.awt.TextField();
        iVentaSaludo = new java.awt.TextField();
        iVentaApellido = new java.awt.TextField();
        iVentaComunaEnt = new java.awt.TextField();
        iVentaModificar = new javax.swing.JButton();
        iVentaBuscarBtn = new javax.swing.JButton();
        iVentaPacks = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        iVentaTelefonoDest = new java.awt.TextField();
        iVentaBanco = new javax.swing.JComboBox<>();
        iVentaCelular = new java.awt.TextField();
        iVentaIngresar = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        ventaFondo = new javax.swing.JLabel();
        consultaClientes = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cCteTelefono1 = new java.awt.TextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        cCteNumeroPedido1 = new java.awt.TextField();
        cCteBusquedaRut1 = new java.awt.TextField();
        cCteRut1 = new java.awt.TextField();
        cCteMail1 = new java.awt.TextField();
        iVentaVentasPendList1 = new javax.swing.JScrollPane();
        cCteventasPendList = new javax.swing.JList<>();
        jLabel55 = new javax.swing.JLabel();
        cCteNombre1 = new java.awt.TextField();
        cCteApellido1 = new java.awt.TextField();
        iVentaBuscarBtn1 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        cCteCelular1 = new java.awt.TextField();
        cCteExportarBtn = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cCteVentasList = new javax.swing.JTable();
        ventaFondo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ventaPestañas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ventaPestañas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ventaPestañas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ventaPestañasStateChanged(evt);
            }
        });
        ventaPestañas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaPestañasMouseClicked(evt);
            }
        });

        iVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        iVenta.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre");
        iVenta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rut");
        iVenta.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Banco");
        iVenta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ingreso Venta");
        iVenta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        iVentaTelefono.setName(""); // NOI18N
        iVentaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaTelefonoActionPerformed(evt);
            }
        });
        iVenta.add(iVentaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total");
        iVenta.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ventas Pendientes");
        iVenta.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Telefono");
        iVenta.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("RRSS");
        iVenta.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Mail");
        iVenta.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fecha Nac.");
        iVenta.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Telefono");
        iVenta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Celular");
        iVenta.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Fecha Entrega");
        iVenta.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Direccion Entrega");
        iVenta.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Destinatario");
        iVenta.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Comuna Entrega");
        iVenta.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Numero Pedido");
        iVenta.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Hora Entrega");
        iVenta.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Saludo");
        iVenta.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        iVentaTotal.setName(""); // NOI18N
        iVentaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaTotalActionPerformed(evt);
            }
        });
        iVenta.add(iVentaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        iVentaNumeroPedido.setName(""); // NOI18N
        iVentaNumeroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaNumeroPedidoActionPerformed(evt);
            }
        });
        iVenta.add(iVentaNumeroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        iVentaBusquedaRut.setName(""); // NOI18N
        iVentaBusquedaRut.setText("12345678-9");
        iVentaBusquedaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaBusquedaRutActionPerformed(evt);
            }
        });
        iVenta.add(iVentaBusquedaRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        iVentaRut.setName(""); // NOI18N
        iVentaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaRutActionPerformed(evt);
            }
        });
        iVenta.add(iVentaRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, -1));

        iVentaMail.setName(""); // NOI18N
        iVentaMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaMailActionPerformed(evt);
            }
        });
        iVenta.add(iVentaMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Seleccion de Pack");
        iVenta.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        iVentaventasPendList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item6", "Item7", "Item8", "Item9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        iVentaVentasPendList.setViewportView(iVentaventasPendList);

        iVenta.add(iVentaVentasPendList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 160, 120));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Apellido");
        iVenta.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        iVentaNombre.setName(""); // NOI18N
        iVentaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaNombreActionPerformed(evt);
            }
        });
        iVenta.add(iVentaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 230, -1));

        iVentaRrss.setName(""); // NOI18N
        iVentaRrss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaRrssActionPerformed(evt);
            }
        });
        iVenta.add(iVentaRrss, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 230, -1));

        iVentaFechaNac.setName(""); // NOI18N
        iVentaFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaFechaNacActionPerformed(evt);
            }
        });
        iVenta.add(iVentaFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 110, -1));

        iVentaDestinat.setName(""); // NOI18N
        iVentaDestinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaDestinatActionPerformed(evt);
            }
        });
        iVenta.add(iVentaDestinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 220, -1));

        iVentaFechaEntrega.setName(""); // NOI18N
        iVentaFechaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaFechaEntregaActionPerformed(evt);
            }
        });
        iVenta.add(iVentaFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 110, -1));

        iVentaHoraEnt.setName(""); // NOI18N
        iVentaHoraEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaHoraEntActionPerformed(evt);
            }
        });
        iVenta.add(iVentaHoraEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 220, -1));

        iVentaDireccionEnt.setName(""); // NOI18N
        iVentaDireccionEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaDireccionEntActionPerformed(evt);
            }
        });
        iVenta.add(iVentaDireccionEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, -1));

        iVentaSaludo.setName(""); // NOI18N
        iVentaSaludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaSaludoActionPerformed(evt);
            }
        });
        iVenta.add(iVentaSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 480, 40));

        iVentaApellido.setName(""); // NOI18N
        iVentaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaApellidoActionPerformed(evt);
            }
        });
        iVenta.add(iVentaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 230, -1));

        iVentaComunaEnt.setName(""); // NOI18N
        iVentaComunaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaComunaEntActionPerformed(evt);
            }
        });
        iVenta.add(iVentaComunaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 220, -1));

        iVentaModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iVentaModificar.setText("Modificar");
        iVentaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaModificarActionPerformed(evt);
            }
        });
        iVenta.add(iVentaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 104, 30));

        iVentaBuscarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iVentaBuscarBtn.setText("Buscar");
        iVentaBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaBuscarBtnActionPerformed(evt);
            }
        });
        iVenta.add(iVentaBuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        iVentaPacks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aniversario  $19.990", "Cumpleaños   $21.990", "Navidad   $25.990", "Matrimonio   $35.990" }));
        iVenta.add(iVentaPacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText(" Ingrese Rut");
        iVenta.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        iVentaTelefonoDest.setName(""); // NOI18N
        iVentaTelefonoDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaTelefonoDestActionPerformed(evt);
            }
        });
        iVenta.add(iVentaTelefonoDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 220, -1));

        iVentaBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco Chile", "Santander" }));
        iVenta.add(iVentaBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, -1));

        iVentaCelular.setName(""); // NOI18N
        iVentaCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaCelularActionPerformed(evt);
            }
        });
        iVenta.add(iVentaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 220, -1));

        iVentaIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iVentaIngresar.setText("Ingresar");
        iVentaIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaIngresarActionPerformed(evt);
            }
        });
        iVenta.add(iVentaIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 104, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 4, 4));
        jLabel47.setText("(12345678-9)");
        iVenta.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        ventaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Spiral730x570 green.jpg"))); // NOI18N
        iVenta.add(ventaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));

        ventaPestañas.addTab("Ingreso Venta", iVenta);

        consultaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        consultaClientes.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre");
        consultaClientes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rut");
        consultaClientes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Consulta Clientes");
        consultaClientes.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        cCteTelefono1.setName(""); // NOI18N
        cCteTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteTelefono1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 220, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Ventas Pendientes");
        consultaClientes.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 140, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Telefono");
        consultaClientes.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Mail");
        consultaClientes.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Celular");
        consultaClientes.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Numero Pedido");
        consultaClientes.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        cCteNumeroPedido1.setName(""); // NOI18N
        cCteNumeroPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteNumeroPedido1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteNumeroPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        cCteBusquedaRut1.setName(""); // NOI18N
        cCteBusquedaRut1.setText("12345678-9");
        cCteBusquedaRut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteBusquedaRut1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteBusquedaRut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        cCteRut1.setName(""); // NOI18N
        cCteRut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteRut1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteRut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, -1));

        cCteMail1.setName(""); // NOI18N
        cCteMail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteMail1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, -1));

        cCteventasPendList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item6", "Item7", "Item8", "Item9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        iVentaVentasPendList1.setViewportView(cCteventasPendList);

        consultaClientes.add(iVentaVentasPendList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 160, 120));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Apellido");
        consultaClientes.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cCteNombre1.setName(""); // NOI18N
        cCteNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteNombre1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 230, -1));

        cCteApellido1.setName(""); // NOI18N
        cCteApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteApellido1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 230, -1));

        iVentaBuscarBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iVentaBuscarBtn1.setText("Buscar");
        iVentaBuscarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVentaBuscarBtn1ActionPerformed(evt);
            }
        });
        consultaClientes.add(iVentaBuscarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 20));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText(" Ingrese Rut");
        consultaClientes.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cCteCelular1.setName(""); // NOI18N
        cCteCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteCelular1ActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 220, -1));

        cCteExportarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cCteExportarBtn.setText("Exportar");
        cCteExportarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCteExportarBtnActionPerformed(evt);
            }
        });
        consultaClientes.add(cCteExportarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 104, 30));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 4, 4));
        jLabel57.setText("(12345678-9)");
        consultaClientes.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        cCteVentasList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Razon Social", "Rut", "Telefono", "Direccion", "Comuna", "Nombre Contacto", "Mail", "Estado"
            }
        ));
        jScrollPane3.setViewportView(cCteVentasList);

        consultaClientes.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 700, 120));

        ventaFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Spiral730x570 green.jpg"))); // NOI18N
        consultaClientes.add(ventaFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 570));

        ventaPestañas.addTab("Consulta Clientes", consultaClientes);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Spiral720x570.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 570));

        ventaPestañas.addTab("Cuansulta Clientes1", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ventaPestañas.addTab("Consulta Venta", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ventaPestañas.addTab("OOCC Pend y Term", jPanel3);

        getContentPane().add(ventaPestañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 730, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iVentaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaTelefonoActionPerformed

    private void iVentaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaTotalActionPerformed

    private void iVentaNumeroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaNumeroPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaNumeroPedidoActionPerformed

    private void iVentaBusquedaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaBusquedaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaBusquedaRutActionPerformed

    private void iVentaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaRutActionPerformed

    private void iVentaMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaMailActionPerformed

    private void iVentaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaNombreActionPerformed

    private void iVentaRrssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaRrssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaRrssActionPerformed

    private void iVentaFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaFechaNacActionPerformed

    private void iVentaDestinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaDestinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaDestinatActionPerformed

    private void iVentaFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaFechaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaFechaEntregaActionPerformed

    private void iVentaHoraEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaHoraEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaHoraEntActionPerformed

    private void iVentaDireccionEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaDireccionEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaDireccionEntActionPerformed

    private void iVentaSaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaSaludoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaSaludoActionPerformed

    private void iVentaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaApellidoActionPerformed

    private void iVentaComunaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaComunaEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaComunaEntActionPerformed

    private void iVentaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaModificarActionPerformed

    private void iVentaBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaBuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaBuscarBtnActionPerformed

    private void iVentaTelefonoDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaTelefonoDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaTelefonoDestActionPerformed

    private void iVentaCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaCelularActionPerformed

    private void iVentaIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaIngresarActionPerformed

    private void ventaPestañasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ventaPestañasStateChanged
        
    }//GEN-LAST:event_ventaPestañasStateChanged

    private void ventaPestañasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaPestañasMouseClicked

    }//GEN-LAST:event_ventaPestañasMouseClicked

    private void cCteTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteTelefono1ActionPerformed

    private void cCteNumeroPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteNumeroPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteNumeroPedido1ActionPerformed

    private void cCteBusquedaRut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteBusquedaRut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteBusquedaRut1ActionPerformed

    private void cCteRut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteRut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteRut1ActionPerformed

    private void cCteMail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteMail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteMail1ActionPerformed

    private void cCteNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteNombre1ActionPerformed

    private void cCteApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteApellido1ActionPerformed

    private void iVentaBuscarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVentaBuscarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iVentaBuscarBtn1ActionPerformed

    private void cCteCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteCelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteCelular1ActionPerformed

    private void cCteExportarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCteExportarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCteExportarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.TextField cCteApellido1;
    public java.awt.TextField cCteBusquedaRut1;
    public java.awt.TextField cCteCelular1;
    public javax.swing.JButton cCteExportarBtn;
    public java.awt.TextField cCteMail1;
    public java.awt.TextField cCteNombre1;
    public java.awt.TextField cCteNumeroPedido1;
    public java.awt.TextField cCteRut1;
    public java.awt.TextField cCteTelefono1;
    public javax.swing.JTable cCteVentasList;
    public javax.swing.JList<String> cCteventasPendList;
    private javax.swing.JPanel consultaClientes;
    private javax.swing.JPanel iVenta;
    public java.awt.TextField iVentaApellido;
    public javax.swing.JComboBox<String> iVentaBanco;
    public javax.swing.JButton iVentaBuscarBtn;
    public javax.swing.JButton iVentaBuscarBtn1;
    public java.awt.TextField iVentaBusquedaRut;
    public java.awt.TextField iVentaCelular;
    public java.awt.TextField iVentaComunaEnt;
    public java.awt.TextField iVentaDestinat;
    public java.awt.TextField iVentaDireccionEnt;
    public java.awt.TextField iVentaFechaEntrega;
    public java.awt.TextField iVentaFechaNac;
    public java.awt.TextField iVentaHoraEnt;
    public javax.swing.JButton iVentaIngresar;
    public java.awt.TextField iVentaMail;
    public javax.swing.JButton iVentaModificar;
    public java.awt.TextField iVentaNombre;
    public java.awt.TextField iVentaNumeroPedido;
    public javax.swing.JComboBox<String> iVentaPacks;
    public java.awt.TextField iVentaRrss;
    public java.awt.TextField iVentaRut;
    public java.awt.TextField iVentaSaludo;
    public java.awt.TextField iVentaTelefono;
    public java.awt.TextField iVentaTelefonoDest;
    public java.awt.TextField iVentaTotal;
    private javax.swing.JScrollPane iVentaVentasPendList;
    private javax.swing.JScrollPane iVentaVentasPendList1;
    public javax.swing.JList<String> iVentaventasPendList;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel42;
    public javax.swing.JLabel jLabel45;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel55;
    public javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel ventaFondo;
    private javax.swing.JLabel ventaFondo1;
    public javax.swing.JTabbedPane ventaPestañas;
    // End of variables declaration//GEN-END:variables
}
